### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by j-corvo** [hsp-iit/behavior-stack-example#3]
Hello, 
I'm trying to compile and run your example, however when I try to execute the command "make" it throws some code errors:

![image](https://user-images.githubusercontent.com/52609366/164441712-3f985da2-4e3c-4b12-b730-47d5eda57598.png)

**Comment by j-corvo** [comment]
I was able to correct the first error but then the next, I don't know how to do it.

![image](https://user-images.githubusercontent.com/52609366/164914074-7f735e07-d195-46ff-84b2-179ae8ca974d.png)

**Comment by miccol** [comment]
Which version of YARP have you installed?

**Comment by j-corvo** [comment]
Yarp version is 3.6.0-2

**Comment by miccol** [comment]
I am on it. I am checking what recent change in YARP is making the code crash. 

Thanks for reporting

**Comment by miccol** [comment]
@j-corvo can you install the latest version of BehaviorTree.CPP and check [this branch](https://github.com/hsp-iit/behavior-stack-example/tree/fix-YARP-36) ?

let me know if you can compile it

**Comment by j-corvo** [comment]
Hi @miccol, 

Thanks a lot for your fast support! With your fix, I was able to compile it successfully!

**Comment by miccol** [comment]
fixed in #5
