### ISSUE TITLE
Nothing happens in example with skills as state charts

### ISSUE THREAD

**Issue by j-corvo** [hsp-iit/behavior-stack-example#4]
Hello @miccol,

I was trying to run the Example with Skills as State Charts and everything seems ok despite the behavior tree transitions. After I run all the xml files it looks like the behavior tree is not being ticked. Should I have to run something else for this example?

This is a screenshot of what happens:
![image](https://user-images.githubusercontent.com/52609366/165935734-06eae419-684a-4c3d-9412-b11f2e13bd16.png)

It also looks like it is stuck in the get method as you can see in the state chart of the condition example.
![image](https://user-images.githubusercontent.com/52609366/165935967-f3971d94-ad48-4b81-91c4-e3e0e0c81172.png)

Thanks in advance for your help!

**Comment by miccol** [comment]
can you check the `main` branch again?

**Comment by j-corvo** [comment]
Yes, I think it's correct now.

Thanks again for your help!
